mnmn: SmartThingsCommunity
vid: 0217e65e-2c22-326c-8e2e-ef9ea830b74f
version: 0.0.1
type: profile
dashboard:
  states:
    - component: main
      capability: switch
      version: 1
      idx: 0
      group: main
      values: []
      composite: false
  actions:
    - component: main
      capability: switch
      version: 1
      idx: 0
      group: main
      inline: null
  basicPlus: []
detailView:
  - component: main
    capability: switch
    version: 1
    values: []
    patch: []
  - component: main
    capability: refresh
    version: 1
    values: []
    patch: []
  - component: channel
    capability: imageafter45121.divoomChannel
    version: 1
    values: []
    patch: []
  - component: system
    capability: switchLevel
    version: 1
    values: []
    patch: []
  - component: system
    capability: temperatureMeasurement
    version: 1
    values: []
    patch: []
automation:
  conditions:
    - component: main
      capability: switch
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: channel
      capability: imageafter45121.divoomChannel
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: system
      capability: switchLevel
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: system
      capability: temperatureMeasurement
      version: 1
      values: []
      patch: []
      exclusion: []
  actions:
    - component: main
      capability: switch
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: channel
      capability: imageafter45121.divoomChannel
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: system
      capability: switchLevel
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: system
      capability: temperatureMeasurement
      version: 1
      values: []
      patch: []
      exclusion: []
presentationId: 0217e65e-2c22-326c-8e2e-ef9ea830b74f
manufacturerName: SmartThingsCommunity
