mnmn: SmartThingsCommunity
version: 0.0.1
type: profile
dashboard:
  states:
    - component: main
      capability: switch
      version: 1
      idx: 0
      group: main
      values: [ ]
      composite: false
  actions:
    - component: main
      capability: switch
      version: 1
      idx: 0
      group: main
      inline: null
  basicPlus: [ ]
detailView:
  - component: main
    capability: switch
    version: 1
    values: [ ]
    patch: [ ]
  - component: main
    capability: refresh
    version: 1
    values: [ ]
    patch: [ ]
  - component: main
    capability: imageafter45121.channel
    version: 1
    values: [ ]
    patch: [ ]
  - component: main
    capability: imageafter45121.cloudChannel
    version: 1
    values: [ ]
    patch: [ ]
    exclusion: [ ]
  - component: main
    capability: imageafter45121.visualizerChannel
    version: 1
    values: [ ]
    patch: [ ]
    exclusion: [ ]
  - component: main
    capability: imageafter45121.customChannel
    version: 1
    values: [ ]
    patch: [ ]
    exclusion: [ ]
  - component: system
    capability: switchLevel
    version: 1
    values: []
#      - key: level.value
#        enabledValues: [ ]
#        range:
#          - 10
#          - 80
#        step: 1
#    patch: [ ]
  - component: system
    capability: temperatureMeasurement
    version: 1
    values: []
#    values:
#      - key: temperature.value
#        label : 99
    patch: [ ]
  - component: system
    capability: imageafter45121.weather
    version: 1
    values: []
  - component: system
    capability: imageafter45121.message
    version: 1
    values: [ ]
automation:
  conditions:
    - component: main
      capability: switch
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: main
      capability: imageafter45121.channel
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: main
      capability: imageafter45121.cloudChannel
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: main
      capability: imageafter45121.visualizerChannel
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: main
      capability: imageafter45121.customChannel
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: system
      capability: switchLevel
      version: 1
      values: []
      patch: [ ]
      exclusion: [ ]
    - component: system
      capability: temperatureMeasurement
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: system
      capability: imageafter45121.weather
      version: 1
      values: [ ]
      patch: [ ]
    - component: main
      capability: imageafter45121.message
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
  actions:
    - component: main
      capability: switch
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: main
      capability: imageafter45121.channel
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: main
      capability: imageafter45121.cloudChannel
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: main
      capability: imageafter45121.visualizerChannel
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: main
      capability: imageafter45121.customChannel
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: system
      capability: switchLevel
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: system
      capability: temperatureMeasurement
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: main
      capability: imageafter45121.message
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
manufacturerName: SmartThingsCommunity
