mnmn: SmartThingsCommunity
version: 0.0.1
type: profile
dashboard:
  states:
    - component: main
      capability: imageafter45121.divoomChannel
      version: 1
      idx: 0
      group: main
      values: [ ]
      composite: false
  actions:
    - component: main
      capability: imageafter45121.divoomChannel
      version: 1
      idx: 0
      group: main
      inline: null
  basicPlus: [ ]
detailView:
  - component: main
    capability: refresh
    version: 1
    values: [ ]
    patch: [ ]
  - component: main
    capability: imageafter45121.divoomChannel
    version: 1
    values: [ ]
    patch: [ ]
  - component: system
    capability: switchLevel
    version: 1
    values: []
#      - key: level.value
#        enabledValues: [ ]
#        range:
#          - 10
#          - 80
#        step: 1
#    patch: [ ]
  - component: system
    capability: temperatureMeasurement
    version: 1
    values: []
#    values:
#      - key: temperature.value
#        label : 99
    patch: [ ]
automation:
  conditions:
    - component: main
      capability: switch
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: system
      capability: imageafter45121.divoomChannel
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: system
      capability: switchLevel
      version: 1
      values:
        - key: level
          enabledValues: [ ]
          range:
            - 10
            - 80
          step: 1
      patch: [ ]
      exclusion: [ ]
    - component: system
      capability: temperatureMeasurement
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: fan
      capability: fanSpeed
      version: 1
      values: [ ]
      patch: [ ]
  actions:
    - component: main
      capability: switch
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: main
      capability: imageafter45121.divoomChannel
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: system
      capability: switchLevel
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: system
      capability: temperatureMeasurement
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: system
      capability: fanSpeed
      version: 1
      values: [ ]
      patch: [ ]
manufacturerName: SmartThingsCommunity
