#smartthings presentation:device-config:create --yaml --input zigbee-tuya-switch-2-deviceConfig.yaml
type: profile
dashboard:
  states:
    - component: main
      capability: switch
      version: 1
      idx: 0
      group: main
      values: [ ]
    - component: switch1
      capability: switch
      version: 1
      idx: 0
      group: switch1
      values: [ ]
    - component: switch2
      capability: switch
      version: 1
      idx: 0
      group: switch2
      values: [ ]
  actions:
    - component: main
      capability: switch
      version: 1
      idx: 0
      group: main
    - component: switch1
      capability: switch
      version: 1
      idx: 0
      group: switch1
    - component: switch2
      capability: switch
      version: 1
      idx: 0
      group: switch2
detailView:
  - component: main
    capability: switch
    version: 1
    values: [ ]
    patch: [ ]
  - component: main
    capability: refresh
    version: 1
    values: [ ]
    patch: [ ]
  - component: switch1
    capability: switch
    version: 1
    values: [ ]
    patch: [ ]
  - component: switch2
    capability: switch
    version: 1
    values: [ ]
    patch: [ ]
automation:
  conditions:
    - component: main
      capability: switch
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: switch1
      capability: switch
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: switch2
      capability: switch
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
  actions:
    - component: main
      capability: switch
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: switch1
      capability: switch
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: switch2
      capability: switch
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
presentationId: e72801a8-0ebf-36ad-a270-80004e8bfcaa
manufacturerName: SmartThingsCommunity
