#smartthings presentation:device-config:create --yaml --input lan-divoom-64-deviceConfig.yaml
type: profile
dashboard:
  states:
    - component: main
      capability: switch
      version: 1
      idx: 0
      group: main
      values: [ ]
  actions:
    - component: main
      capability: switch
      version: 1
      idx: 0
      group: main
detailView:
  - component: main
    capability: switch
    version: 1
    values: [ ]
    patch: [ ]
  - component: main
    capability: refresh
    version: 1
    values: [ ]
    patch: [ ]
  - component: switch1
    capability: switch
    version: 1
    values: [ ]
    patch: [ ]
  - component: Device Sensor
    capability: temperatureMeasurement
    version: 1
    values: [ ]
    patch: [ ]
automation:
  conditions:
    - component: main
      capability: switch
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: switch1
      capability: switch
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: Device Sensor
      capability: temperatureMeasurement
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
  actions:
    - component: main
      capability: switch
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: switch1
      capability: switch
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
    - component: Device Sensor
      capability: temperatureMeasurement
      version: 1
      values: [ ]
      patch: [ ]
      exclusion: [ ]
presentationId: 991f387b-7e7e-3095-8a02-5f137c57c3c2
manufacturerName: SmartThingsCommunity