#smartthings capabilities:presentation:create imageafter45121.divoomChannel 1 --yaml --input=divoom-channel-presentation.yaml
---
dashboard:
  states:
    - label: "{{channel.value}}"
  actions: [ ]
  basicPlus: [ ]
detailView:
  - label: Channel Select
    displayType: list
    list:
      command:
        name: setChannel
        alternatives:
          - key: 0
            value: Faces
          - key: 1
            value: Cloud Channel
          - key: 2
            value: Visualizer
          - key: 3
            value: Custom
          - key: 4
            value: Black Screen
        supportedValues: supportedChannels.value
      state:
        value: channel.value
        alternatives:
          - key: 0
            value: Faces
          - key: 1
            value: Cloud Channel
          - key: 2
            value: Visualizer
          - key: 3
            value: Custom
          - key: 4
            value: Black Screen
automation:
  conditions:
    - label: Channel Select
      displayType: list
      list:
        value: channel.value
        alternatives:
          - key: 0
            value: Faces
          - key: 1
            value: Cloud Channel
          - key: 2
            value: Visualizer
          - key: 3
            value: Custom
          - key: 4
            value: Black Screen
  actions:
    - label: Channel Select
      displayType: list
      list:
        command: setChannel
        alternatives:
          - key: 0
            value: Faces
          - key: 1
            value: Cloud Channel
          - key: 2
            value: Visualizer
          - key: 3
            value: Custom
          - key: 4
            value: Black Screen
        supportedValues: supportedChannels.value
id: imageafter45121.divoomChannel
version: 1