#smartthings capabilities:presentation:create imageafter45121.divoomChannel 1 --yaml --input=divoom-channel-presentation.yaml
#smartthings capabilities:presentation:update imageafter45121.divoomChannel 1 --yaml --input=divoom-channel-presentation.yaml
---
dashboard:
  states:
    - label: "{{channel.value}}"
  actions: []
  basicPlus: []
detailView:
  - label: Channel 설정
    displayType: list
    list:
      command:
        name: setChannel
        alternatives:
          - key: Auto
            value: 아열대 쾌적
          - key: Wind
            value: 청정
          - key: Cool
            value: 냉방
          - key: Dry
            value: 제습
          - key: DryClean
            value: 청정 제습
          - key: CoolClean
            value: 청정 냉방
        supportedValues: supportedDivoomChannels.value
      state:
        value: channel.value
        alternatives:
          - key: Auto
            value: 아열대 쾌적
          - key: Wind
            value: 청정
          - key: Cool
            value: 냉방
          - key: Dry
            value: 제습
          - key: DryClean
            value: 청정 제습
          - key: CoolClean
            value: 청정 냉방
automation:
  conditions:
    - label: Channel 설정
      displayType: list
      list:
        value: channel.value
        alternatives:
          - key: Auto
            value: 아열대 쾌적
          - key: Wind
            value: 청정
          - key: Cool
            value: 냉방
          - key: Dry
            value: 제습
          - key: DryClean
            value: 청정 제습
          - key: CoolClean
            value: 청정 냉방
  actions:
    - label: Channel 설정
      displayType: list
      list:
        command: setChannel
        alternatives:
          - key: Auto
            value: 아열대 쾌적
          - key: Wind
            value: 청정
          - key: Cool
            value: 냉방
          - key: Dry
            value: 제습
          - key: DryClean
            value: 청정 제습
          - key: CoolClean
            value: 청정 냉방
        supportedValues: supportedChannels.value
id: imageafter45121.divoomChannel
version: 1